from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

from rdkit import Chem

from poly_csp.io.pdb import write_pdb_from_rdkit


def _write_placeholder_inpcrd(mol: Chem.Mol, path: Path) -> None:
    conf = mol.GetConformer(0)
    xyz = conf.GetPositions()
    natom = mol.GetNumAtoms()
    lines = ["poly_csp AMBER inpcrd placeholder", f"{natom:6d}"]
    values = []
    for i in range(natom):
        px, py, pz = xyz[i]
        values.extend([float(px), float(py), float(pz)])
    for i in range(0, len(values), 6):
        chunk = values[i : i + 6]
        lines.append("".join(f"{v:12.7f}" for v in chunk))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_placeholder_prmtop(path: Path) -> None:
    text = (
        "%VERSION  VERSION_STAMP = V0001.000  DATE = 01/01/2026\n"
        "%FLAG TITLE\n%FORMAT(20a4)\n"
        "PLACEHOLDER PRMTOP GENERATED BY poly_csp.\n"
        "This file is a scaffold and is not parameterized.\n"
    )
    path.write_text(text, encoding="utf-8")


def export_amber_artifacts(
    mol: Chem.Mol,
    outdir: str | Path,
    model_name: str = "model",
    charge_model: str = "bcc",
    parameter_backend: str = "placeholder",
) -> Dict[str, object]:
    """
    Stage-8 scaffold exporter.
    Produces deterministic handoff files for downstream parameterization.
    """
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)

    pdb_path = out / f"{model_name}.pdb"
    prmtop_path = out / f"{model_name}.prmtop"
    inpcrd_path = out / f"{model_name}.inpcrd"
    tleap_path = out / "tleap.in"
    manifest_path = out / "amber_export.json"

    write_pdb_from_rdkit(mol, pdb_path)
    _write_placeholder_prmtop(prmtop_path)
    _write_placeholder_inpcrd(mol, inpcrd_path)
    tleap_path.write_text(
        "\n".join(
            [
                "source leaprc.gaff2",
                f"mol = loadpdb {pdb_path.name}",
                "# TODO: load frcmod/off/lib from parameterization pipeline",
                f"saveamberparm mol {prmtop_path.name} {inpcrd_path.name}",
                "quit",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    summary: Dict[str, object] = {
        "enabled": True,
        "parameterized": False,
        "charge_model": charge_model,
        "parameter_backend": parameter_backend,
        "files": {
            "pdb": str(pdb_path),
            "prmtop": str(prmtop_path),
            "inpcrd": str(inpcrd_path),
            "tleap_input": str(tleap_path),
        },
        "notes": [
            "Files are deterministic scaffold artifacts.",
            "prmtop/inpcrd are placeholders until parameterization backend is integrated.",
        ],
    }
    manifest_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    summary["manifest"] = str(manifest_path)
    return summary
