defaults:
  - topology/backbone: amylose
  - topology/selector: dmpc_35
  - structure/helix: chiralpak_ad
  - forcefield/options: vacuum_stiff_backbone
  - ordering: basic
  - forcefield: mixing_rules
  - qc: basic
  - multi_opt: default
  - _self_

output:
  dir: outputs
  export_formats: [pdb, sdf, amber]

amber:
  enabled: true
  dir: amber
